### ISSUE TITLE
Why are the dimensions this size?  Can they be different numbers?

### ISSUE THREAD

**Issue by Jason-Do** [gauravkuppa/pong-from-pixels#11]
https://github.com/gauravkuppa/pong-from-pixels/blob/3e98aea9ba3127a69574b71ed0d20a7c3bdef472/pong-from-pixels.py#L23

**Comment by gauravkuppa** [comment]
I think that one of the repos found that this dimensionality worked better than the original 80 x 80. it seems that there is no reason to use a smaller dimensionality other than the fact that empircal results improved
