### ISSUE TITLE
What is use of prepro when setting up the environment?

### ISSUE THREAD

**Issue by spencer-enriquez** [gauravkuppa/pong-from-pixels#12]
https://github.com/gauravkuppa/pong-from-pixels/blob/3e98aea9ba3127a69574b71ed0d20a7c3bdef472/pong-from-pixels.py#L36

**Comment by gauravkuppa** [comment]
The purpose is to remove borders, downsample the images to a space the image to a place where the neural network is able to understand the movements and of the paddle and ball. 

View the comments next to each action in the prepro() method. There is an explanation of exactly what is happening.
