### ISSUE TITLE
Does the cPickle library provide any additional functionality other than storing trained models / weight values?

### ISSUE THREAD

**Issue by spencer-enriquez** [gauravkuppa/pong-from-pixels#13]
https://github.com/gauravkuppa/pong-from-pixels/blob/3e98aea9ba3127a69574b71ed0d20a7c3bdef472/pong-from-pixels.py#L6

**Comment by gauravkuppa** [comment]
nope! it is used to save and reload existing models and associated weights, there are no additional functionalities for the sake of this code
