### ISSUE TITLE
Do gamma and decay rates have to be the same? is 0.99 the highest it can go? how is the learning different with a lower gamma rate?

### ISSUE THREAD

**Issue by PushpalPatil** [gauravkuppa/pong-from-pixels#2]
https://github.com/gauravkuppa/pong-from-pixels/blob/ea5f2b521dac2e847c7d3964d1319a69a71aa447/pong-from-pixels.py#L15

**Comment by gauravkuppa** [comment]
Gamma and decay rates are similar in terms of what they are doing, but they are being used for two different functions. Gamma rate is to discount the reward function, whereas the decay rate is used for RMSProp, which the optimizer function we use.

So, no they do not have to be the same. 1 is the highest you can go. A lower gamma rate will shift importance from accumulated gradients to current gradients. In other words, you will allow the model to be more suspectible to noise that new gradients bring in. Additionally, this gives new gradients more importance, which still could be important. That would allow the model to sufficiently update the model's parameters.
