### ISSUE TITLE
What is the purpose of this vstack function?

### ISSUE THREAD

**Issue by Jason-Do** [gauravkuppa/pong-from-pixels#8]
https://github.com/gauravkuppa/pong-from-pixels/blob/fa8c9028da1eb39451f0760acbe87aa98db71db2/pong-from-pixels.py#L122

**Comment by gauravkuppa** [comment]
the vstack function stacks numpy array vertically on top of each other. in this case, xs is the observation state for the current step. we save that observation state by vertically stacking it in the value epx
